### PR TITLE
Field status feature

### PR DESCRIPTION
**Pull request by Sina-pz**
nv-dropdown-component
nv-style-directive

### CODE REVIEW

**Review by veeranjaneyuludavuluri — COMMENTED** [review]
While testing this functionality locally observed when selected item length is more showing 3 dots, while changing drop down those 3 dots rendering in red color, I feel it is not user friendly to show like that, it indicates some error. Fix it.

**Comment by Sina-pz** [comment]
> While testing this functionality locally observed when selected item length is more showing 3 dots, while changing drop down those 3 dots rendering in red color, I feel it is not user friendly to show like that, it indicates some error. Fix it.

I did not see the red color; please elaborate more

**Review by veeranjaneyuludavuluri — COMMENTED** [review]
Your changes looks good, but while running locally noticed drop down error icons size  is larger compared to input text box.

**Comment by Sina-pz** [comment]
> ns size is larger compared to input text box.

Please elaborate more " icons compared to input text box! " I checked and the size of icons are identical

**Pull request merged**
